name: share
description: Flutter plugin for sharing content via the platform share UI.
version: 1.0.0
author: Aleksei Sturov
homepage: https://github.com/Alezhka/flutter_share

environment:
  sdk: '>=2.12.2 <3.0.0'
  flutter: '>=2.0.0'

flutter:
  plugin:
    androidPackage: io.flutter.plugins.share
    iosPrefix: FLT
    pluginClass: SharePlugin

dependencies:
  meta: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.3
  flutter_test:
    sdk: flutter
